### ISSUE TITLE
CPU between 80% - 95% of usage on RT-AC86U

### ISSUE THREAD

**Issue by carlos-gva** [RMerl/asuswrt-merlin.ng#248] opened 2019-01-18 22:24 UTC
After upgrading from **v384.7** to **384.8_2** the two cores of the CPU are always on high usage.

I downgraded to **v384.8** and the issue still happens. So I downgraded again (to **v384.7_2**) and the issue does not occur.

I detected this issue without doing anything on the router, I mean, I just logged in and checked the CPU usage.

In my case, the router is working on AP mode.

**Comment by Geezus42** [comment] 2019-01-23 13:18
https://github.com/RMerl/asuswrt-merlin.ng/issues/163

**Comment by Geezus42** [comment] 2019-01-28 21:34
This sounds like a Duplicate of #163.

**Comment by crkinard** [comment] 2019-05-24 22:39
I have had avahi freak out after a reboot at times and run a core full tilt till I restart the service.

**Comment by riobard** [comment] 2019-06-07 11:20
Same problem here. `top` shows the process `[bcmsw_rx]` is constantly using 40~50% CPU. 

RT-AC86U in dumb AP mode with nothing else configured. Firmware version is 384.11_2.

**Comment by jrowe88** [comment] 2020-03-22 15:12
I have the same issue with [bcmsw_rx] using 0-50% of the over all CPU and pegging individual cores.  This happens any time one of my laptops is accessing data off the LAN.  Specific case:  I have a NAS (open media vault) connected to the router's switch with 1GB NIC.  I then use Adobe Light Room from a laptop connected to either the 5 or 2.4G WIFI to access files on that NAS.  As soon as this starts, one of the CPU cores starts shooting up.  It varies, but as you can see by the graph in the image, it is non-stop.  This has the result of slowing everything else on the network down.

This has to be a bug.  I never experienced this with my Asus AC68U stock firmware.  The router experiencing this problem is:  RT-AX88U / Version:  384.15_0

It does not seem to matter whether I have AI protection or QoS on.  They are off when the image attached was taken.

I've seen numerous posts on this for some years.  I've tried all the suggestions and using top/ps, it is always [bcmsw_rx] process, not jffs, or other culprits.  Shouldn't the router be able to pass traffic within its limits and do so without grinding the network to a halt for all other clients!?

![image](https://user-images.githubusercontent.com/10144594/77252846-3b6b6700-6c1c-11ea-983e-4eff592d213e.png)

**Closed** 2020-09-21 21:04 UTC
