### ISSUE TITLE
160MHz (5GHz) Bandwidth on RT-AC88U

### ISSUE THREAD

**Issue by Germandoe** [RMerl/asuswrt-merlin.ng#578] opened 2020-08-09 00:51 UTC
Since a few recent updates, my RT-AC88U has been showing 160MHz option under Wireless. I've tested it and the 5GHz wifi does not intialize on the 160MHz setting, It works flawlessly on 80MHz or lower tho.

Could this be an Asus bug? I have the latest Beta version at the moment, however this issue was present on 384.18 as well.

![Screenshot_6](https://user-images.githubusercontent.com/17865871/89722591-afe84c00-d9eb-11ea-8c26-2f0bf0be6c31.png)

Have a good day and thank you for your software!

**Comment by paldier** [comment] 2020-08-13 03:24
you should use a non-china version device, these wifi chips are different models, but they are all named 4366 or 4366e

**Comment by npmstart-pray** [comment] 2020-08-13 11:03
You know the old story about the person who goes to see their doctor with the complaint “it hurts when I do this”?  The doctor tells the patient “well don’t do that”. 
You should consider following the doctor’s advice. Or, check the original specification of the router to determine if it will indeed support 5ghz wifi with 160MHz.

**Comment by Germandoe** [comment] 2020-08-14 23:33
> you should use a non-china version device, these wifi chips are different models, but they are all named 4366 or 4366e

The one I have is the EU version. Odd.



> You know the old story about the person who goes to see their doctor with the complaint “it hurts when I do this”? The doctor tells the patient “well don’t do that”.
> You should consider following the doctor’s advice. Or, check the original specification of the router to determine if it will indeed support 5ghz wifi with 160MHz.

Sounds about right. Tho I secretly wish ASUS added 160MHz support 😄 The RT-AC88U has only 80MHz out-of-the-box.

**Comment by paldier** [comment] 2020-08-24 01:49
> 
> 
> > you should use a non-china version device, these wifi chips are different models, but they are all named 4366 or 4366e
> 
> The one I have is the EU version. Odd.
> 
> > You know the old story about the person who goes to see their doctor with the complaint “it hurts when I do this”? The doctor tells the patient “well don’t do that”.
> > You should consider following the doctor’s advice. Or, check the original specification of the router to determine if it will indeed support 5ghz wifi with 160MHz.
> 
> Sounds about right. Tho I secretly wish ASUS added 160MHz support 😄 The RT-AC88U has only 80MHz out-of-the-box.

The EU version hardware support 160, but the number of channels is not enough, you have to change the territory_code to AA/US/AU in cfe, i don't think you like this.

**Comment by RMerl** [comment] 2020-09-21 21:00
Known issue probably caused by the frankenbuild required to support that model in 384.19, I'd expect it to be fixed in future releases.

**Closed by RMerl** 2020-09-21 21:00 UTC
