### ISSUE TITLE
DDNS returns wrong IP

### ISSUE THREAD

**Issue by alexander-hagen** [RMerl/asuswrt-merlin.ng#302] opened 2019-04-24 04:06 UTC
DDNS returns wrong IP address on 384.10_2, but also have the same issue on previous version. Router: AC88U

I have configured the same DDNS service with NO-IP on a Synology NAS in my LAN, but using a different DDNS hostname. The IP address returned by NO-IP on the Synology NAS is correct, whereas the IP address returned by the AC88U is incorrect.

![AC88U DDNS](https://user-images.githubusercontent.com/27280136/56631736-2c390d80-6689-11e9-83ae-b4459261c457.PNG)
![DS412](https://user-images.githubusercontent.com/27280136/56631737-2c390d80-6689-11e9-8478-47f04f281155.PNG)
![NoIP](https://user-images.githubusercontent.com/27280136/56631738-2c390d80-6689-11e9-91ba-74167a7e2f0f.PNG)

**Comment by RMerl** [comment] 2019-04-24 05:40
The external check merely use whatever IP is detected by the remote server.  If your ISP uses some form of transparent web proxy, that might disrupt results.  Use the Internal check instead of external then, it will use the IP obtained by your router from the ISP.

Closing this, as this is not a bug of the firmware.

**Closed by RMerl** 2019-04-24 05:40 UTC
