### ISSUE TITLE
Только имя пользователя / пароль0

### ISSUE THREAD

**Issue by YBS-PC** [RMerl/asuswrt-merlin.ng#357] opened 2019-09-09 20:42 UTC
in vpn client tab there is '0' after text
in English Username / Password Auth. Only
in Russian Только имя пользователя / пароль0

asus rt ac88u
merlin 384.13

**Comment by RMerl** [comment] 2019-09-11 13:59
The issue is upstream.  I don't make changes to the dict files since it would be far too much work to maintain afterward, so it will have to be fixed by Asus.

**Closed by RMerl** 2019-09-11 13:59 UTC
